name: senzu_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #C
  cloud_firestore: ^4.0.5
  charts_flutter: ^0.10.0
  cupertino_icons: ^1.0.3

  #F
  firebase_auth: ^4.1.2
  flutter_spinkit: ^5.0.0
  firebase_core: ^2.2.0
  font_awesome_flutter: ^9.0.0
  flutter_svg: ^0.22.0
  flutter_launcher_icons: ^0.9.0

  #H
  http: ^0.13.3

  #I
  intl: ^0.17.0

  #P
  path_provider: ^2.0.2
  percent_indicator: ^3.0.1
  provider: ^6.0.4

  #U
  url_launcher: ^6.0.6


flutter_icons:
  image_path: "assets/app_launcher_icon/senzu_icon.png" 
  android: true
  ios: true



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/meal_icons/
    - assets/login_screen/
    - assets/app_launcher_icon/


  fonts:
    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
